[build-system]
requires = ["setuptools", "torch"]
build-backend = "setuptools.build_meta"

[project]
name = "l1attn_cpp"
version = "0.1.0"

[tool.setuptools]
py-modules = ["l1attn_cpp", "l1attn_sparse_cpp"]